act_type: Tanh
bs: 4096
clip_eps: 0.2
dir: data/foragax/std/
env_aperture_size: 15
env_name: ForagaxTwoBiomeSmall-v2
g: 0.99
h_dim:
- 64
- 64
label: Standard PPO
lm: 0.8
lr: 0.001
n_itrs: 4
n_slices: 32
n_steps: 1e6
ob_norm: 0
rew_norm: 0
seed: 0
to_log:
- pol_features_activity
- pol_weights
- val_weights
- stable_rank
- weight_change
u_adv_scl: 1
u_epi_ups: 0
